wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.0
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1700714650.783564
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.8.18
      5: 0.16.0
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
